services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work.
    # The best practice is to be explicit about your dependencies anyway.

  jinya_profiling.event_subscriber:
    alias: JinyaProfiling\Bundle\EventSubscriber\JinyaProfilerEventSubscriber

  JinyaProfiling\Bundle\Formatting\DataFormatter:
    autowire: true
  JinyaProfiling\Bundle\Formatting\DataFormatterInterface: '@JinyaProfiling\Bundle\Formatting\DataFormatter'

  JinyaProfiling\Bundle\Formatting\DoctrineDataCollectorFormatter:
    autowire: true
  JinyaProfiling\Bundle\Formatting\DoctrineDataCollectorFormatterInterface: '@JinyaProfiling\Bundle\Formatting\DoctrineDataCollectorFormatter'

  JinyaProfiling\Bundle\Formatting\ProfileFormatter:
    autowire: true
  JinyaProfiling\Bundle\Formatting\ProfileFormatterInterface: '@JinyaProfiling\Bundle\Formatting\ProfileFormatter'

  JinyaProfiling\Bundle\Formatting\RequestDataCollectorFormatter:
    autowire: true
  JinyaProfiling\Bundle\Formatting\RequestDataCollectorFormatterInterface: '@JinyaProfiling\Bundle\Formatting\RequestDataCollectorFormatter'

  JinyaProfiling\Bundle\Formatting\TwigDataCollectorFormatter:
    autowire: true
  JinyaProfiling\Bundle\Formatting\TwigDataCollectorFormatterInterface: '@JinyaProfiling\Bundle\Formatting\TwigDataCollectorFormatter'

  JinyaProfiling\Bundle\EventSubscriber\JinyaProfilerEventSubscriber:
    arguments:
      $profiler: '@Symfony\Component\HttpKernel\Profiler\Profiler'
      $profilerOutDir: ''
      $profilerEnabled: true
      $profileFormatter: '@JinyaProfiling\Bundle\Formatting\ProfileFormatter'